// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVHpG69j1xRQki0HaScmSJbAa_MMi8XAI',
    appId: '1:137604299072:web:0bbf61f95b148e73d462a5',
    messagingSenderId: '137604299072',
    projectId: 'chatapp-b2ab6',
    authDomain: 'chatapp-b2ab6.firebaseapp.com',
    storageBucket: 'chatapp-b2ab6.appspot.com',
    measurementId: 'G-Z8QM4FG63N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcEZcHRhe4UFin6O0kfZQoTWtrPLHZoC4',
    appId: '1:137604299072:android:7d2821ef3e3debf4d462a5',
    messagingSenderId: '137604299072',
    projectId: 'chatapp-b2ab6',
    storageBucket: 'chatapp-b2ab6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA902FUdLF0NewrAz5gM-mHfXjclRkdis8',
    appId: '1:137604299072:ios:c8931e7e3db48dd3d462a5',
    messagingSenderId: '137604299072',
    projectId: 'chatapp-b2ab6',
    storageBucket: 'chatapp-b2ab6.appspot.com',
    iosClientId: '137604299072-7a7pneif8rtktod60lo8grcib5eejpof.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA902FUdLF0NewrAz5gM-mHfXjclRkdis8',
    appId: '1:137604299072:ios:c8931e7e3db48dd3d462a5',
    messagingSenderId: '137604299072',
    projectId: 'chatapp-b2ab6',
    storageBucket: 'chatapp-b2ab6.appspot.com',
    iosClientId: '137604299072-7a7pneif8rtktod60lo8grcib5eejpof.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
